// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int times = Integer.parseInt(args[0]);

		int countBelowHalf = 0; // Count the amount of times the generated number was below 0.5.
		int countAboveHalf = 0; // Count the amount of times the generated number was above (or equal to) 0.5.

		double randomNum;

		for (int i = 0; i < times; i++) {
			randomNum = Math.random();

			if (randomNum < 0.5) {
				countBelowHalf++;
			} else countAboveHalf ++;
		}

		double ratio =  countAboveHalf > 0 ?  countBelowHalf / (double) countAboveHalf : 0;

		System.out.println("> 0.5: " + countBelowHalf + " times");
		System.out.println("<= 0.5: " + countAboveHalf + " times");
		System.out.println("Ratio: " + ratio);
	}
}
